### ISSUE TITLE
Converted file size is too big

### ISSUE THREAD

**Issue by SooperPooperApp** [alexcorvi/heic2any#32]
Converted file size from regular image shot by Iphone camera is 10 times larger in result comparing 1.8mb & 16mb in result.

**Comment by randolf** [comment]
One of the features of the HEIC/HEIF format is to provide better compression, so it's normal that converting to a lossless format like PNG or a lossy format like JPeG results in a larger target file size in most circumstances.

I have had success with converting HEIC images to WebP using ImageMagick, and sometimes receiving a smaller file size since WebP (which is supported by all modern web browsers these days) was also designed to provide better compression.  I find that it depends on the image though as some images compress better in different algorithms given the arbitrary nature of the contents of the image itself.
